site_name: Plasmid-borne integron database

theme:
  name: material

nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - Tutorial: tutorial.md
  - Workflow: workflow.md

plugins:
  - search

extra_css:
  - https://cdn.datatables.net/1.13.7/css/jquery.dataTables.min.css

extra_javascript:
  - https://code.jquery.com/jquery-3.7.1.min.js
  - https://cdn.datatables.net/1.13.7/js/jquery.dataTables.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/PapaParse/5.4.1/papaparse.min.js
  - js/tables.js
